stages:
  - build

build_windows:
  stage: build
  image: golang:latest
  variables:
    GOARCH: amd64
    GOOS: windows
    CGO_ENABLED: 0
  script:
    -go build -o ./app_windows_amd64.exe
  artifacts:
    paths:
      - ./app_windows_amd64.exe

build_linux:
  stage: build
  image: golang:latest
  variables:
    GOARCH: amd64
    GOOS: linux
    CGO_ENABLED: 0
  script:
    -go build -o ./app_linux_amd64
  artifacts:
    paths:
      - ./app_linux_amd64

build_mac:
  stage: build
  image: golang:latest
  variables:
    GOARCH: amd64
    GOOS: darwin
    CGO_ENABLED: 0
  script:
    -go build -o ./app_mac_amd64
  artifacts:
    paths:
      - ./app_mac_amd64

build_mac_arm:
  stage: build
  image: golang:latest
  variables:
    GOARCH: arm64
    GOOS: darwin
    CGO_ENABLED: 0
  script:
    -go build -o ./app_mac_arm64
  artifacts:
    paths:
      - ./app_mac_arm64
