before_script:
  - export GO111MODULE=on  # Ensure modules are enabled
  - export GOPROXY=https://proxy.golang.org,direct  # Use the Go module mirror
  - mkdir -p $CI_PROJECT_DIR/go/bin
  - mkdir -p $CI_PROJECT_DIR/go/pkg
  - mkdir -p $CI_PROJECT_DIR/go/src
  - export GOPATH=/opt/homebrew/bin/go
  - export PATH=$PATH:$GOPATH/bin

stages:
  - build

build_windows:
  stage: build
  variables:
    GOARCH: amd64
    GOOS: windows
    CGO_ENABLED: 0
  script:
    - go build -o ./app_windows_amd64.exe
  artifacts:
    paths:
      - ./app_windows_amd64.exe

build_linux:
  stage: build
  variables:
    GOARCH: amd64
    GOOS: linux
    CGO_ENABLED: 0
  script:
    - go build -o ./app_linux_amd64
  artifacts:
    paths:
      - ./app_linux_amd64

build_mac:
  stage: build
  variables:
    GOARCH: amd64
    GOOS: darwin
    CGO_ENABLED: 0
  script:
    - go build -o ./app_mac_amd64
  artifacts:
    paths:
      - ./app_mac_amd64

build_mac_arm:
  stage: build
  variables:
    GOARCH: arm64
    GOOS: darwin
    CGO_ENABLED: 0
  script:
    - go build -o ./app_mac_arm64
  artifacts:
    paths:
      - ./app_mac_arm64
